//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public int admin_id { get; set; }
        public string a_name { get; set; }
        public string a_email { get; set; }
        public string a_password { get; set; }
        public string a_address { get; set; }
        public string a_mobile { get; set; }
        public byte[] a_photo { get; set; }
    }
}
