//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public int c_id { get; set; }
        public string category_name { get; set; }
        public string category_code { get; set; }
        public string category_image { get; set; }
        public string category_price { get; set; }
    }
}
