//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryAssign
    {
        public int assignid { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> db_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public Nullable<System.DateTime> da_date { get; set; }
    
        public virtual tblDeliveryboy tblDeliveryboy { get; set; }
        public virtual tblRestuarantRegistration tblRestuarantRegistration { get; set; }
    }
}
