//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryboy
    {
        public tblDeliveryboy()
        {
            this.tblDeliveryAssigns = new HashSet<tblDeliveryAssign>();
        }
    
        public int db_id { get; set; }
        public string db_name { get; set; }
        public string db_mobile { get; set; }
        public Nullable<int> r_id { get; set; }
        public string db_status { get; set; }
    
        public virtual ICollection<tblDeliveryAssign> tblDeliveryAssigns { get; set; }
    }
}
