//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int payment_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string payment_mode { get; set; }
        public string payment_status { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
    }
}
