//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int review_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public string description { get; set; }
        public Nullable<double> rating { get; set; }
    
        public virtual tblRestuarantRegistration tblRestuarantRegistration { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
