//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRestuarantRegistration
    {
        public tblRestuarantRegistration()
        {
            this.tblDeliveryAssigns = new HashSet<tblDeliveryAssign>();
            this.tblReviews = new HashSet<tblReview>();
        }
    
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string r_mobileno { get; set; }
        public string r_emailid { get; set; }
        public string r_address { get; set; }
        public string r_description { get; set; }
        public string r_status { get; set; }
        public string rest_image { get; set; }
        public string r_pwd { get; set; }
        public Nullable<System.DateTime> r_lastdate { get; set; }
    
        public virtual ICollection<tblDeliveryAssign> tblDeliveryAssigns { get; set; }
        public virtual ICollection<tblReview> tblReviews { get; set; }
    }
}
