//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubcategory
    {
        public int s_id { get; set; }
        public string subcategory_name { get; set; }
        public string subcategory_code { get; set; }
        public string subcategory_image { get; set; }
        public string subcategory_price { get; set; }
        public Nullable<int> c_id { get; set; }
    }
}
