//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSpecial
    {
        public int offer_id { get; set; }
        public string offer_image { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<int> r_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string status { get; set; }
        public Nullable<decimal> offer_price { get; set; }
        public string offer_desc { get; set; }
        public string f_name { get; set; }
        public string offer_name { get; set; }
        public string oldprice { get; set; }
    }
}
