//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblReviews = new HashSet<tblReview>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_mobile { get; set; }
        public string user_email { get; set; }
        public string user_address { get; set; }
        public string user_status { get; set; }
        public string user_pwd { get; set; }
    
        public virtual ICollection<tblReview> tblReviews { get; set; }
    }
}
